### ISSUE TITLE
Error validating a Json-schema with the adapter "PropertyTreeAdapter"

### ISSUE THREAD

**Issue by davtorresg** [tristanpenman/valijson#10]
Following the example "external_schema.cpp", I have implemented an example with the adapter "PropertryAdapter". I have used as input parameters the schema and json used in the test  "test_validation_error.cpp" (files "allof_integers_and_numbers.schema.jason" and "array_doubles_1_2_3.json")

Trying to validate this we get the error "Failed to parse schema: JSON value is not a boolean". 

Basically, my example does:
1) ptree schemaDocument
2) Schema schema
3) SchemaParser parser
4) PropertryTreeAdapter schemaDocumentAdapter
5) parser.populateSchema(schemaDocumentAdapter, schema)

The code is faling in the method "parser.populateSchema(...)"

If I pass these files to the example "external_schema.cpp" it works correctly.

**Comment by tristanpenman** [comment]
Based on a quick review of the code that parses the constraints in that schema, it looked like it would be failing at the 'uniqueItems' constraint, as the boolean value was being parsed using strict typing. I've changed this in 29367cc.

**Comment by tristanpenman** [comment]
I've also fixed similar bugs for 'additionalItems' and 'required' constraints in 222e593.

**Comment by davtorresg** [comment]
Thank you very much. Now my example returns the same result that the example "external_schema.cpp"
