### ISSUE TITLE
Add Conan package

### ISSUE THREAD

**Issue by mathbunnyru** [tristanpenman/valijson#100]
It would be nice to be able to use this package in conan

**Comment by mathbunnyru** [comment]
This issue is actually to let you know, that I already made a package.

https://github.com/conan-io/conan-center-index/pull/3068/

I will close the issue as soon as the package will be merged.

**Comment by tristanpenman** [comment]
👍

**Comment by mathbunnyru** [comment]
Done.

**Comment by tristanpenman** [comment]
Thanks for the contribution!
