### ISSUE TITLE
Add compiler flag for disabling exceptions

### ISSUE THREAD

**Issue by baylesj** [tristanpenman/valijson#106]
Some projects, specifically Chromium in my case, do not allow exceptions to be used in the code base (`-fno-exceptions`). That means, unfortunately, that libraries like `valijson` cannot be used.

We have solved this with other libraries, like JsonCpp, through a compiler flag that enables/disables exceptions. For an example, see https://github.com/open-source-parsers/jsoncpp/issues/972, where we set JSON_USE_EXCEPTION=0 to use JsonCpp without exceptions.

Personally, I'm generally a fan of exceptions but don't really have any flexibility when working inside Chromium. I'm willing to do the work to get this compiler flag added, but wanted to post an issue to ensure that we could actually get it checked in if implemented.

**Comment by tristanpenman** [comment]
This is something that I am willing to support, as I'm all for making it easier for other projects to make use of the library. In fact, I would go as far as to remove the use of exceptions entirely.

Here's my thinking.... Although exceptions are exposed through the valijson API (specifically when parsing schemas and when using parser adapters directly), they are not something that I consider to be an important aspect of the API. In the places where they are exposed, we could quite easily use an alternative such as `std::optional`. Also, there isn't much internal logic that relies on catching exceptions to validate documents.

I'm more than happy to collaborate in making these changes, and if you're interested in pursuing it, I can offer some suggestions as to how to stage the work. My thinking is that this is something that could be developed in a 1.0 branch, with other potentially breaking changes (validation error reporting, in particular).

**Comment by baylesj** [comment]
That sounds awesome to me. I really like valijson as a library and would love to see it picked up in Chromium. We tend to do some support work as well, and push security fixes so I think it's a plus for libraries we pick up too.

I'm definitely interested in pursuing it, what would your ideal patch progression look like? I have some bandwidth over the next week or two and would be down to invest some time into getting this added.

**Comment by tristanpenman** [comment]
I'm going to close this issue for now, as #110 has been merged and appears to be working well. I've created a 1.0-dev branch which I'm using for any more significant changes, and will track any further work on exceptions there.
