### ISSUE TITLE
Deprecated add_definitions CMake properties should be updated

### ISSUE THREAD

**Issue by baylesj** [tristanpenman/valijson#111]
In CMake 3.1.2, the `add_definitions` directive has been replaced with a set of more specific definition specifiers, such as [`add_compile_definitions`](https://cmake.org/cmake/help/latest/command/add_compile_definitions.html#command:add_compile_definitions).

The minimum CMake version should be set to 3.1.2 and the new directives swapped out for the deprecated ones.

**Comment by tristanpenman** [comment]
Hey @baylesj, I finally got around to making these changes. They're in commit c2822576a2ab53ee9990db2243173dfddad86376.

I'll close this issue for now, but feel free to reopen it if you have any related suggestions.
