### ISSUE TITLE
Bad logic parsing a schema with if/then/else subschemas

### ISSUE THREAD

**Issue by BSipos-RKF** [tristanpenman/valijson#118]
When a schema is parsed which contains a conditional constraint, the current (version 0.3 and master) logic does not properly decode the sub-schemas and the resulting state causes an infinite recursion (i.e. a stack explosion) and crash.

After digging some I have a rough patch which at least causes the schema to be parsed correctly and seems to validate conditions correctly. The issue was that all of the if/then/else subtrees were being accessed with identical path name and so the cache was treating them as identical subtrees (thus the condition contained the condition itself, causing recursion).

**Comment by tristanpenman** [comment]
Merged in 635f36f
