### ISSUE TITLE
cannot the project with valijson when nlohmann json is provided by the system

### ISSUE THREAD

**Issue by michal-kowalczyk** [tristanpenman/valijson#122]
I use the nlohmann json library installed on ubuntu 20.04 in the following way:
```bash
apt install -y nlohmann-json3-dev
```

The header files are located under:
`/usr/include/nlohmann`
e.g.
`/usr/include/nlohmann/json.hpp`

I add that library to my project in the following way:
```cmake
find_package(nlohmann_json REQUIRED)
target_link_libraries(my_target LINK_PUBLIC nlohmann_json::nlohmann_json)
```

I include the header file in this way:
```c++
#include <nlohmann/json.hpp>
```

Now, I add valijson to my project according to instruction from README:
```cmake
set(valijson_BUILD_TESTS OFF)
add_subdirectory(extern/valijson)
target_link_libraries(my_target LINK_PUBLIC nlohmann_json::nlohmann_json ValiJSON::valijson)
```

Unfortunately, the compilation fails due to missing header `json.hpp` included in `valijson/adapters/json11_adapter.hpp`

I worked this around by modifying valijson target so that `nlohmann/json.hpp` can be included as `json.hpp`:
```cmake
target_include_directories(valijson INTERFACE /usr/include/nlohmann)
```

But it does not seem to be a clean solution (and most likely should be mentioned in the README).

**Comment by tristanpenman** [comment]
See how you go with the changes in 66262ba. I've updated the header files for nlohmann json support so that they include json.hpp using the correct path (i.e. including the `nlohmann/` prefix).

If it still causes trouble for your project, feel free to re-open this issue.

**Comment by michal-kowalczyk** [comment]
Thanks @tristanpenman for prompt fix! It works like a charm.
