### ISSUE TITLE
Support fetching sub-schemas from other files

### ISSUE THREAD

**Issue by alexlavriv** [tristanpenman/valijson#126]
The spec contains a definition for fetching schemas from other files, not only remote URIs:
https://json-schema.org/understanding-json-schema/structuring.html

`{ "$ref": "definitions.json#/address" }`

The current implementation calls to the fetch function only when the ref contains "://" - as in "HTTP://", "https://" and so on.
In order to make it fetch a local file had to work around it, and set it as `{ "$ref": "://definitions.json#/address" }`.
Please add support for fetching sub-schemas from local files.

**Comment by matty0ung** [comment]
I had the same need, so I've proposed a fix: https://github.com/tristanpenman/valijson/pull/135/

**Comment by tristanpenman** [comment]
This has been merged in b1119cccd66f9fdbee9e95fbf392ba42b42bc8ed and will be included in a v0.6 release shortly.

Feel free to open a new issue if you think that this can be improved further.
