### ISSUE TITLE
MSVC C4702: Unreachable Code

### ISSUE THREAD

**Issue by DrewMikola** [tristanpenman/valijson#130]
For example:

````C++
    template<typename AllocatorType>
    static JsonType jsonTypeFromString(const std::basic_string<char,
            std::char_traits<char>, AllocatorType> &typeName)
    {
        if (typeName.compare("any") == 0) {
            return kAny;
        } else if (typeName.compare("array") == 0) {
            return kArray;
        } else if (typeName.compare("boolean") == 0) {
            return kBoolean;
        } else if (typeName.compare("integer") == 0) {
            return kInteger;
        } else if (typeName.compare("null") == 0) {
            return kNull;
        } else if (typeName.compare("number") == 0) {
            return kNumber;
        } else if (typeName.compare("object") == 0) {
            return kObject;
        } else if (typeName.compare("string") == 0) {
            return kString;
        }

        throwRuntimeError("Unrecognised JSON type name '" +
                std::string(typeName.c_str()) + "'");
        abort(); //UNREACHABLE
    }
````

That last abort is unreachable and will break builds where warnings are treated as errors if exceptions are disabled.   If exceptions are enabled then one could argue that calling `abort` here is appropriate, however if exceptions are disabled for valijson the `throwRuntimeError` function calls `abort` internally.

There are 3 instances of this issue:
* json_pointer.hpp(235): warning C4702: unreachable code
* json_pointer.hpp(245): warning C4702: unreachable code
* concrete_constraints.hpp(1209): warning C4702: unreachable code

**Comment by tristanpenman** [comment]
Hi @DrewMikola thanks for reporting the issue. As I've just explained in issue #125 a lot of these warnings depend on the level of optimisation and inlining applied. While the warnings are correct, there were so many of them, that I believe it would harm the readability of the code to attempt to structure it in a way that avoids them (not to mention, I hardly have enough time to maintain this library these days). Instead, I've decided to silence those warnings for just the relevant headers.

I just tested this with exceptions disabled, and the approach seems to work well. You'll find these changes in commit c63ac26.

Hopefully that is an acceptable solution for your use case. Feel free to re-open the issue should you have any other ideas about how to handle this.

**Comment by DrewMikola** [comment]
Thank you for the update @tristanpenman ! I totally understand, the line has to be drawn somewhere.  Thanks!
