### ISSUE TITLE
Non-moveable types due to const data members

### ISSUE THREAD

**Issue by mporsch** [tristanpenman/valijson#138]
I store schemata and validators to quickly validate input data. This is made unnecessary hard as some types are non-moveable (e.g. https://github.com/tristanpenman/valijson/blob/master/include/valijson/validator.hpp#L70) while there seems to be no need to do so (i.e. being registered somewhere else by address). To my best knowledge there is no performance benefit in data constness, i.e. the compiled byte code is the same either way.

**Comment by tristanpenman** [comment]
Hi @mporsch thanks for raising this issue, and apologies for the slow reply. Your suggestion makes good sense, so I've removed some of the obviously redundant `const` declarations in 26f3a84. Hopefully that will make Valijson more suitable for your use case.

I'm going to close this issue for now, but please re-open it if there are any more unnecessary `const` declarations that are a problem for you.
