### ISSUE TITLE
Numeric type accepts a string containing only numbers

### ISSUE THREAD

**Issue by xgsa** [tristanpenman/valijson#140]
I have tried the external_schema.cpp example with the following file:
Schema: `{"type":"number"}`
Data: `"12"`
This passes validation, whereas according to the [Understanding JSON schema](https://json-schema.org/understanding-json-schema/reference/type.html) manual it shouldn't. Thus, it looks like a bug. Am I missing something?

**Comment by tristanpenman** [comment]
I think this can be attributed to a weakness in the documentation. On line 60 of 'external_schema.cpp' you'll see that the `Validator` class is instantiated with the `Validator::kWeakTypes` argument. This allows the validator to opportunistically cast types if that allows them to be successfully. So a string `"23"` will validate as a number `23`, as long as the cast doesn't fail. You can change that to `Validator::kStrongTypes` to get the behaviour you expect.

The main reason this was added to Valijson was to support the Boost Property Tree library, which can parse JSON, but uses string types to store data. It probably makes sense to change this example code to use a strongly typed validator. I'll think about that for a while, but it's likely that I'll change it :)

**Comment by tristanpenman** [comment]
For the record, I've updated the example and made a note of this in the README in 75ada05.

Thanks for raising the issue 👍
