### ISSUE TITLE
Compiler error caused by missing include

### ISSUE THREAD

**Issue by mporsch** [tristanpenman/valijson#143]
After only including validator.hpp, I stumble on a compiler error about missing std::function here https://github.com/tristanpenman/valijson/blob/75ada05cf809a20758879eeafe7127c88e407a47/include/valijson/subschema.hpp#L38
Adding an `#include <functional>` to the file fixes it for me.

**Comment by tristanpenman** [comment]
Thanks for reporting the issue. This should be fixed in 4a99dd7. Feel free to re-open this issue if this does not fix the problem.
