### ISSUE TITLE
::operator new will throw instead of returning nullptr

### ISSUE THREAD

**Issue by mporsch** [tristanpenman/valijson#144]
Regular `new` will never return a `nullptr`; instead it throws `std::bad_alloc`. See 'Exceptions' in https://en.cppreference.com/w/cpp/memory/new/operator_new

In the library `operator new` is used as default if no custom allocator is given.
`nullptr` seems to be expected by all functions using the custom allocator, e.g. https://github.com/tristanpenman/valijson/blob/master/include/valijson/constraints/basic_constraint.hpp#L42
So even if used without `VALIJSON_USE_EXCEPTIONS`, the code will throw if out of memory. (Or is this somehow covered by the `_HAS_EXCEPTIONS` preprocessor macro?)

As a fix, a short wrapper that adds the `std::nothrow` argument to `new` can be used

```
diff --git a/include/valijson/internal/custom_allocator.hpp b/include/valijson/internal/custom_allocator.hpp
index 07e1d61..292ac34 100644
--- a/include/valijson/internal/custom_allocator.hpp
+++ b/include/valijson/internal/custom_allocator.hpp
@@ -29,7 +29,7 @@ public:
     };
 
     CustomAllocator()
-      : m_allocFn(::operator new),
+      : m_allocFn([](size_t size) { return ::operator new(size, std::nothrow); }),
         m_freeFn(::operator delete) { }
 
     CustomAllocator(CustomAlloc allocFn, CustomFree freeFn)
diff --git a/include/valijson/subschema.hpp b/include/valijson/subschema.hpp
index 68acf1d..2a25a02 100644
--- a/include/valijson/subschema.hpp
+++ b/include/valijson/subschema.hpp
@@ -47,7 +47,7 @@ public:
      * @brief  Construct a new Subschema object
      */
     Subschema()
-      : m_allocFn(::operator new)
+      : m_allocFn([](size_t size) { return ::operator new(size, std::nothrow); })
       , m_freeFn(::operator delete)
       , m_alwaysInvalid(false) { }
 
```

**Comment by tristanpenman** [comment]
Thanks for the suggestion, and apologies for the slow reply.

I've implemented this in db8daacc3297bd50bcde3c6d62cfbaf8ff911923, so hopefully that meet your needs. I'm going to close this issue for now, but feel free to re-open it if it doesn't.
