### ISSUE TITLE
CMake improvements

### ISSUE THREAD

**Issue by jonpetri** [tristanpenman/valijson#146]
Hi, @tristanpenman @baylesj 
 
I have recently integrated valijson in a project, using CMake features (find_package...) and I noticed that some improvements can be done to valijson. Let's discuss it a bit, I'll propose merge requests later. There are several points:

- Configuration file missing:
Once valijson installed, it cannot be found (by a project willing to use it) with cmake's find_package command. This is just because the cmake configuration file is not created and installed bay valijson. Do you agree to add it? (this is just 2 commands to add)

- valijson_INSTALL_HEADERS
I think this parameter is not necessary. Valijson has only headers to install, and the install step is done separately from the build. The user does `cmake --build <xx>` and then `cmake --install` separately. So when one does `cmake --install`, he wants the header to be installed, for sure. I think `valijson_INSTALL_HEADERS` makes it just more difficul. We could remove this parameter from the cmakefile?

- valijson_BUILD_TESTS
This in ON by default, and adds unnecessary dependencies to valijson. Valijson itself doesn't need Boost, pico..., but if the tests are built they become a dependency, which is not true. (For instance in my case I have Qt, but not Boost). So I propose to set `valijson_BUILD_TESTS` OFF by default. Again, this is to simplify cmake usage). What do you think?
(This last point will change valijson's behavior, not building the test by default)

**Comment by tristanpenman** [comment]
Hi @jonpetri, thanks for taking the time to write up your suggestions. All three of those make sense to me, and I'd be surprised if they introduced non-trivial incompatibilities with projects that have already integrated Valijson through CMake.

As you've already noticed, @baylesj has previously made a number of changes to improve CMake integration. If you want to raise a PR with your suggested changes, I'll be happy to merge it, but will keep it open for a couple of weeks to give him a chance to respond.

**Comment by tristanpenman** [comment]
Closing now that #150 has been merged.
