### ISSUE TITLE
single-header release?

### ISSUE THREAD

**Issue by dmarkh** [tristanpenman/valijson#149]
Hi, would it be possible to provide a single-header release of valijson? I understand that packaging everything in one header may be too much, but, say, a single header containing everything compatible with nlohmann json would be great since nlohmann json library has single-header version releases.

Thanks!

**Comment by tristanpenman** [comment]
Hi @dmarkh, thanks for the suggestion. It does sound a like nice thing to have, but  I don't have much time to work on Valijson these days, so probably won't get a chance to look at this myself. My main concern is avoiding a situation where every release requires a new single header version of the library to be generated. Are you aware of any tools that might be appropriate for handling this?

**Comment by tristanpenman** [comment]
I had a go at implementing something that may help with this. Commit 1ff36254826ea88935ce280ef587c66096c5d7d2 adds a `bundle.sh` script, which can be used to generate a single header file for a given adapter. This header contains all of the common classes required for loading schemas and performing validation.

An example has been included in the `examples` directory for Nlohmann Json.

I'm going to close this issue for now, but let me know if you have any ideas for how to make this better.
