### ISSUE TITLE
Web version of valijson

### ISSUE THREAD

**Issue by letmaik** [tristanpenman/valijson#152]
I made a web version of valijson, maybe someone finds it useful for quickly testing valijson's capabilities without doing a source build:

Website: https://letmaik.github.io/valijson-wasm/
Repo: https://github.com/letmaik/valijson-wasm

Feel free to close this issue again, since it's not an actual issue...

Screenshot:
![image](https://user-images.githubusercontent.com/530988/152029940-0acfd6b0-4569-4567-96bc-cc4d07701b2a.png)

**Comment by tristanpenman** [comment]
This is pretty neat. Thanks for letting me know about it!

Would you mind if I included the repo and github.io links in the valijson README?

**Comment by letmaik** [comment]
Sure, go ahead! Glad you like it :)

**Comment by tristanpenman** [comment]
Added to the README in 3940b36 👏
