### ISSUE TITLE
Question about library Dependencies

### ISSUE THREAD

**Issue by jparisu** [tristanpenman/valijson#155]
Hi there,
I would like to use this library to validate YAML files, using `yamlcpp` library to convert from YAML to JSON.
This intends to go in a middleware dynamic library for public use.

I yet do not totally get the dependencies management of this library.
**Is it that every supported and required library is included in thirdparty?**

If so:
**If I already have my `yamlcpp` library installed (as well as others as gtest and nlohmann/json), using this library will force me to download and install them again?**

I agree with issue https://github.com/tristanpenman/valijson/issues/149 , this will make much more sense.
And it would be much easier for the users to maintain.

**Comment by tristanpenman** [comment]
Hi @jparisu, my plan is to switch to using sub-modules for the dependencies in `/thirdparty` at some point in the near future. Hopefully that will address some of the confusion around how to include Valijson as part of other projects.

As it is, you should be able to include Valijson in your project without any of the dependencies in `/thirdparty`. These are only used for the test suite and examples.

For regular usage, the only time a particular parser library is required is when its Adapter class is used. e.g. if you use `valijson::adapters::RapidJsonAdapter`, then that will require RapidJSON to be in the compiler's include and library paths. So in practice, the unused header files are not even compiled into your code.

If you really wanted to strip things down, you could also safely remove the header files for the adapters that you don't want to use.

Does that address your concerns?

**Comment by jparisu** [comment]
Thank you @tristanpenman for the quick reply.
I see we can make a fork/vendor of your repository and just leave those files that we need. Yet, I am not sure this is the approach we will take, we have to study it.

Thank you anyway for this project and your time.
