### ISSUE TITLE
Implement population of "default" values in documents

### ISSUE THREAD

**Issue by carlsmedstad** [tristanpenman/valijson#157]
Firstly, thanks for a great library!

When we implemented this in our code base one useful feature that came to mind was population of `default` values for missing keys / values.

I imaging the interface would look something like this:

```cpp
json myDocument;
valijson::Schema mySchema;

std::cout << "Before:" << std::endl;
std::cout << myDocument.dump(2) << std::endl;

valijson::defaultPopulator;
defaultPopulator.populate(myDocument, mySchema);

std::cout << "After:" << std::endl;
std::cout << myDocument.dump(2) << std::endl;
```

This would output:

```text
Before:
{
  "input" : 123
}
After:
{
  "input": 123,
  "my_default": "asd"
}
```

When using a schema like this:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "example",
  "type": "object",
  "properties": {
    "my_default": {
      "type": "string",
      "default": "asd"
    }
  }
}
```

I'd be happy to try to implement this if this sounds like a good idea. Thanks!

**Comment by tristanpenman** [comment]
Hey @carlsmedstad, thanks for taking the time to write this up, and sorry it took me so long to respond to the issue. This is an interesting idea, but the main challenge I see with it is that the existing parser adapters only support read operations. It would be a lot of work to retrofit write operations. Given that it is also something that deviates from the original purpose of the library, it's also likely that the feature would not be well-maintained.

I'll be interested to see if you come up with something for this, even if it is parser-specific. In the mean time, I'm going to close this issue. Feel free to re-open it if you still think the idea is worth exploring.
