### ISSUE TITLE
Newer Rapidjson?

### ISSUE THREAD

**Issue by tysenmoore-xse** [tristanpenman/valijson#161]
We are using rapidjson with valijson and updated the gcc compiler to 11.2. It turns out rapidjson has issues with that compiler [#1924](https://github.com/Tencent/rapidjson/issues/1924). The bug has been fixed in rapidjson (Sept 24, 2021). 

Would it be possible to get an updated version of rapidjson to something post Sept 24, 2021 checked into valijson?

**Comment by tristanpenman** [comment]
It should be relatively easy to compile using a different version of RapidJSON. Although the bundled RapidJSON is used for the test suite and example code, when you include Valijson headers in your own project, it will use whatever version of RapidJSON is found in your system include path.

In any case, I'll leave this issue open as a reminder to check for newer versions of the bundled parsers. And perhaps finally move to using Git submodules!

**Comment by tristanpenman** [comment]
The bundled version of rapidjson has been converted to a git submodule and updated to the latest commit from the upstream repo. This was done in 2642dd4efcddd58d318ca695bddf3c7c3fe10c5a.

I'm going to close this issue as resolved for now, but feel free to re-open it if you still have problems with this.
