### ISSUE TITLE
Qt bundle script: missing #include <limits>

### ISSUE THREAD

**Issue by ilario-gottardello** [tristanpenman/valijson#162]
When generating a bundle for Qt types, the resulting header file will not compile correctly because "\<limits\>" is included after usage.
The first point where it is needed is on line 2490 but the header is included only at line 2981. Adding an include before that fixes the problem.

I am using valijson version 0.7 from Releases

**Comment by tristanpenman** [comment]
Can you let me know if commit [d397ac6](https://github.com/tristanpenman/valijson/commit/d397ac6074096ad4c09063d0523efa3a8b315c6d) addresses the issue for you?

**Comment by tristanpenman** [comment]
Closing this for now, since the issue should be resolved. Please re-open this issue if you are still having trouble with this.
