### ISSUE TITLE
Updated release please.

### ISSUE THREAD

**Issue by cbrumgard** [tristanpenman/valijson#176]
Could we get an updated official release with the recent changes and have the conan repo updated, please?

**Comment by tristanpenman** [comment]
Will do.

**Comment by tristanpenman** [comment]
https://github.com/conan-io/conan-center-index/pull/17621

**Comment by cbrumgard** [comment]
Thank you so much.  Let me know if there is anything in valijson I can work on as thanks.

**Comment by tristanpenman** [comment]
This has been bumped in conan, as per https://github.com/tristanpenman/conan-center-index/commit/4b794f52f7dc56ccb17dd419c6ea2435212ce19f

Feel free to re-open this issue if you run into any issues with this.
