### ISSUE TITLE
Roadmap to support Draft 8 / Draft 8.1

### ISSUE THREAD

**Issue by hcw70** [tristanpenman/valijson#194]
Are there any plans on supporting later drafts from https://json-schema.org/specification-links ?

**Comment by tristanpenman** [comment]
At this stage, there are no plans for support of future drafts. When doing this in the past, I've generally added a new constant to `SchemaParser` to identify the in-progress draft [here](https://github.com/tristanpenman/valijson/blob/master/include/valijson/schema_parser.hpp#L34). I also try to incorporate any updated test cases from https://github.com/json-schema-org/JSON-Schema-Test-Suite. Once those are in place, it's a matter of working through the test cases until support is relatively complete.

It'll be a while before I can do any of this myself, but I'm more than happy to facilitate implementation of later draft support.

**Comment by hcw70** [comment]
Thank you for this statement. 
We are currently investigating different options for JSON / YAML schemas.

But no concrete action currently needed.
