### ISSUE TITLE
RapidJSON Adapter member access issue in rapidjson_adapter.hpp

### ISSUE THREAD

**Issue by jasonthorsness** [tristanpenman/valijson#195]
other.itr should be other.m_itr

https://github.com/tristanpenman/valijson/blob/a0e05907ae3f54df2d0bd7d83e3c7b73abe3aae9/include/valijson/adapters/rapidjson_adapter.hpp#L726

```
    std::ptrdiff_t difference(const GenericRapidJsonArrayValueIterator<ValueType> &other)
    {
        return std::distance(m_itr, other.itr);
    }
```

https://github.com/tristanpenman/valijson/blob/a0e05907ae3f54df2d0bd7d83e3c7b73abe3aae9/include/valijson/adapters/rapidjson_adapter.hpp#L823

```
    std::ptrdiff_t difference(const GenericRapidJsonObjectMemberIterator &other)
    {
        return std::distance(m_itr, other.itr);
    }
```

breaks compilation of this header under emcc

**Comment by tristanpenman** [comment]
This should be fixed in fc9ddf14db683c9443c48ae3a6bf83e0ce3ad37c
