### ISSUE TITLE
adding valijson package to buildroot

### ISSUE THREAD

**Issue by santoshmulthalli** [tristanpenman/valijson#26]
below is the pull request
https://github.com/tristanpenman/valijson/pull/25
 things I had to modify to adapt to build root system are
1) remove -werror from CMAKE_CXX_FLAGS
2) add options to provide either install headers , build examples or build valijson test
3) by default install all headers.

**Comment by tristanpenman** [comment]
Closing this issue since the PR was merged back in April.
