### ISSUE TITLE
Clarify draft 4 exceptions

### ISSUE THREAD

**Issue by larsimmisch** [tristanpenman/valijson#27]
Hi,

README.md states that: 

> The exceptions for Draft 4 are:  
> - definitions format (optional)

But when I try to validate:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#iso8601-date-time",
  "title": "valijson definitions schema",
  "type": "object",
  "definitions": {
    "rational": {
      "type": "array",
      "minItems": 2,
      "maxItems": 2,
      "items": {
        "type": "integer"
      }
    }
  },
  "properties": {
    "rationalValue": {
      "$ref": "#/definitions/rational"
    }
  },
  "additionalProperties": false,
  "minProperties": 1
}
```

with the document:

`{ "rationalValue": [1, 2, 3] }`

I get the error message _Array should contain no more than 2 elements._ and a path of `[ "<root>", "[rationalValue]" ]`.

So to me this looks as if definitions are in fact supported; what do you mean in README.md?

(This is very nice, BTW, I like it a lot. Thank you)

**Comment by tristanpenman** [comment]
It looks like you're correct. The README probably needs a few other revisions since $ref support was added, but I've removed the offending line.

Thanks for pointing that out.
