### ISSUE TITLE
How can I validate a simple string literal or std::string?

### ISSUE THREAD

**Issue by Substance12** [tristanpenman/valijson#38]
What I'm trying to do assumes that the file could not be a JSON sometimes, and if I try loading a non-valid JSON with a library (so I can use an adapter) it just crashes (programming for a Nintendo 3DS so there's no proper way to handle errors). How can I use this with strings to make sure they're valid JSONs or not?

**Comment by tristanpenman** [comment]
As a JSON _Schema_ validator, Valijson is only designed to operate on an abstract representation of a JSON document. That was one of the motivations for including adapters for various JSON parsers. 

What you're trying to do is validate JSON syntax. So what you'll need to do is look at each of the parsers (that can be compiled for the 3DS) and see what they recommend for handling JSON syntax errors.
