### ISSUE TITLE
Resolv remote schemas

### ISSUE THREAD

**Issue by cumafo** [tristanpenman/valijson#39]
Hi
I have a question why remote resolver callbacks are not made for non-absolute paths.
I my case I have access to some schemas and schemas components, all in same directory and all references are relative to the same directory.
I can’t modify the schemas since they are used by other applications.
Right now I solved it by modify findAbsoluteDocumentUri in schema_parser.hpp to return also a relative path, if present.
Anyway – thanks for a great piece of software.
/c

**Comment by tristanpenman** [comment]
Given that this is such an old issue, I'm guessing that it may no longer be relevant. I am going to close it for now, but feel free to re-open it if this is still an issue.
