### ISSUE TITLE
Replace u_int32_t by uint32_t

### ISSUE THREAD

**Issue by Jarod42** [tristanpenman/valijson#4]
As noted in http://stackoverflow.com/questions/5163835/what-is-u-int32-t
`u_int32_t` is not standard whereas `uint32_t` is.

So use in include\valijson\utils\utf8_utils.hpp the standard type.

The current work-around is to do:

    using u_int32_t = uint32_t;

before including the valijson headers.

**Comment by tristanpenman** [comment]
Thanks for the tip Jarod. This has been fixed in commit e601e10.
