### ISSUE TITLE
has_include not available pre-c++ 17.0

### ISSUE THREAD

**Issue by WilliamClements** [tristanpenman/valijson#42]
Using library in Visual Studio 2015. The has_include not available pre-c++ 17.0. To resolve compilation error I wrote this line before including the headers:

#define __has_include(x) 0

**Comment by dpower-lv** [comment]
Same on Ubuntu with GCC6.
This is not surprisising as __has_include_ is part of the C++17 spec.

**Comment by tristanpenman** [comment]
This should be fixed in c2f22fd.

Let me know if it is still an issue for you.

**Comment by WilliamClements** [comment]
Thank you for the fix! I will let you know if similar problem recurs when I try it.
