### ISSUE TITLE
MaxItemsConstraint warnings

### ISSUE THREAD

**Issue by NamtarR** [tristanpenman/valijson#46]
Hello! I use valijson in my project and I have to get rid of all warnings before I can finish it. So, I've got warnings in `concrete_constraints.hpp` complaining about uint64_t variable being implicitly truncated to size_t. My project is to be run on a 32-bit processor and thus size_t size is 32bits so this might be an issue someday. Of course I don't use 64bit integers in constraints but still I can't finish my project with such warnings during building. What can we do about it?

**Comment by tristanpenman** [comment]
This has been fixed by @drolevar's recent PR, which was merged in commit f68cd48.
