### ISSUE TITLE
Valijson with multi-level schemas

### ISSUE THREAD

**Issue by monstasat** [tristanpenman/valijson#48]
In my previously submitted issue (#47) , I've posted some code which handles validation of nlohmann json object using schema like this:

```
json j_schema =
        json{{"comment", "JSON schema for Options class"},
             {"type", "object"},
             {"required", {"prop3"}},
             {"properties", {{"prop1", {"type", "array"}},
                             {"prop2", {"type", "object"}},
                             {"prop3", {"type", "number"}}}}};
```

This schema has some root-level rules (`"type":"object"`, `"required":["prop1"]`) and child-level rules for `prop1, prop2` and `prop3`. Does valijson support validation at all levels of schema, or validation is handled only for the root-level? Sorry for posting such a simple question here, but I couldn't test it by myself yet because of the issue described in #47.

**Comment by cmannett85** [comment]
> Does valijson support validation at all levels of schema...?

Yes.
