### ISSUE TITLE
Miss-leading validation errors when using combining keywords

### ISSUE THREAD

**Issue by falstaff84** [tristanpenman/valijson#50]
When validating against a JSON schema with combining keywords, spurious errors might appear. If the JSON file is valid this is not a problem since errors get simply ignored. However, in case validation fails, the library user can no longer tell which validation issues are actually relevant.

The attached example leads to this spurious error when using the `external_schema` example application:

    Validation failed.
    Error #1
      context: <root>
      desc:    Missing required property 'name'.
    Error #2
      context: <root>[id]
      desc:    Value type not permitted by 'type' constraint.
    Error #3
      context: <root>
      desc:    Failed to validate against schema associated with property name 'id'.

[example_valijson.zip](https://github.com/tristanpenman/valijson/files/1199054/example_valijson.zip)

**Comment by tristanpenman** [comment]
Thanks for the PR @falstaff84. I have merged your changes.
