### ISSUE TITLE
Questions about valijson in Windows

### ISSUE THREAD

**Issue by checor** [tristanpenman/valijson#52]
Hi! I'm checking your project and seems that is the library that I've been looking for. I want to use to validate some shcemas in Qt.

However, I'm a noob when it come to build using CMake. I don't know if there are some optional dependencies. For example, If I only want Qt integration, can I set off the Poco integration?

I'm having that trouble compiling using VS2013 in Win10. Icould help with some documentation, if someone can help me with the building.

Thanks!

**Comment by lennartS-7cs** [comment]
Hi,

there is no need to build `valijson` itself with CMake if you just want to use `valijson`. Just point your include directory list in Visual Studio to the `include` directory of `valijson` and use the Qt integration.

I just adapted the RapidJson example from the ReadMe, just use
```
#include <valijson/adapters/qtjson_adapter.hpp>
#include <valijson/utils/qtjson_utils.hpp>
```

Hope that helps.

**Comment by checor** [comment]
Good! That way I can try to use it.

However, there are some errors when I try to compile with MSVC 2013, in optional.hpp

It seems that is a Boost-related library, so maybe using a different version of it would work.

I will try in my own to compile this, but, if you have the time to give me an insight, I will appreciate it.

Thanks!

**Comment by tristanpenman** [comment]
Hey @checor, I recently updated 'optional.hpp' to address the fact that the __has_include macro is not available prior to C++17. I think this will help with your compile errors.

Let me know if you still have problems with the latest code.
