### ISSUE TITLE
Any plans for a release?

### ISSUE THREAD

**Issue by luisremis** [tristanpenman/valijson#57]
Hi, 

Thanks for this library, great work. 

I am planning to use it for a project I am working on, and I was wondering if you have any plans to make an official release/pre-release.  

Thanks again.

**Comment by tristanpenman** [comment]
Thanks, Luis. There are no plans for an official release at this stage. However I would like to better understand any ways in which an official (pre-)release could be helpful, as I would be happy to do a bit of work on that if it will make it easier for other developers to integrate Valijson in their projects.

**Comment by luisremis** [comment]
Thanks for your reply. 

By creating a release, it is easier and more practical for me to ask the user of my project to download and install your library. Instead of asking people to clone your repo and go to a specific commit, I can ask people to just download a release from the release section on github (for example: https://github.com/google/protobuf/releases ). 

It is easier for us to support (find problems, plan releases) our software if we are sure people are using the same snapshot of your library we used when we tested our project (that snapshot being a release  with specific version number). 

As I am sure you know, github allows you to easily create releases using tags in git. So, having a tag pointing a specific commit and marked as a release would make adoption of your library for us much simpler. 

Thanks for considering this option and let me know if you need more information.

**Comment by kawakaze** [comment]
Hi,

This would also help me.
Right now if I want to document my usage of your library or to archive it somewhere I need to use the current git commit as tag 4da82347373896f8b6f37f6f961974c330e8f7db to know what I archived. While it is possible it does not seem clean.
I'm way more used to the way jsoncpp releases their product (https://github.com/open-source-parsers/jsoncpp/releases). I know which version I'm currently using, I can check with the release note what changed in the new version (maybe you updated an adapter I'm not using, maybe you are now on the latest version of the draft.
This would also allow you to control when users should use your repository (allowing you to possibly start a new feature breaking everything and still commit your code).

**Comment by tristanpenman** [comment]
Better late than never, hopefully.

I've created an official v0.1 pre-release, which you can find here: https://github.com/tristanpenman/valijson/releases/tag/v0.1

**Comment by nicolasdehouck** [comment]
thanks

**Comment by luisremis** [comment]
This is great, thanks!
