### ISSUE TITLE
Is boost actually a required dependency?

### ISSUE THREAD

**Issue by drdavella** [tristanpenman/valijson#63]
If so, then it needs to be added to the "Dependencies" section of the README.

Ideally I wouldn't need to install Boost if I didn't intend to use the Boost JSON parser. However, it looks like `valijson` actually relies on Boost for other parts of its implementation as well?

**Comment by drdavella** [comment]
A little more digging suggests the answer is actually "no". But it looks like if I want to actually install the library using CMake, I can't do it without having Boost and curlpp installed (and possibly some others). 

This isn't ideal: I really should be able to configure the build and install the library without having any additional dependencies that might only be required for testing.

**Comment by tristanpenman** [comment]
You'll be glad to know that, after a very long pause in development, Boost has been made a truly optional dependency, even for the test suite.
