### ISSUE TITLE
CMake: Prefix option variables

### ISSUE THREAD

**Issue by sebastianst** [tristanpenman/valijson#66]
Please prefix your option variables `INSTALL_HEADERS`, `BUILD_EXAMPLES` and `BUILD_TESTS` with `${PROJECT_NAME}_` to clearly mark them as belonging to valijson. I use valijson in a project with dozens of other dependencies and it is quite confusing to see those seemingly global variables in ccmake.
(The option `BUILD_TESTS` is particularly confusing because there's CTest's `BUILD_TESTING` variable)

It is generally good cmake practice to prefix all variables with global scope.

**Comment by tristanpenman** [comment]
Closing this now that your changes have been merged.

Thank you very much for your efforts, and sorry about the delay in merging this!
