### ISSUE TITLE
CMake: Define valijson targets for target_link_libraries

### ISSUE THREAD

**Issue by sebastianst** [tristanpenman/valijson#67]
I currently include valijson in my project with
```
target_include_directories(sel PRIVATE "extern/valijson/include")
```
However, it would be better to use the more modern `target_link_libraries` for which there would be the need for a target like `valijson::valijson` or even sub-targets depending on the adapter one wants to use, e.g. `valijson::nlohmann` etc.

Or is it already possible to use taget_link_libraries and I'm missing something?

**Comment by arthurafarias** [comment]
Hey I tried to solve this with creating an interface target in the pull request number. #92 .

**Comment by tristanpenman** [comment]
Thanks @arthurafarias for the contribution. I've merged that PR, so I'm going to close this ticket. Please feel free to re-open it if there are any other issues related to this.
