### ISSUE TITLE
Some typo in test_jsoncpp_adapter.cpp

### ISSUE THREAD

**Issue by dota17** [tristanpenman/valijson#78]
[line 15](https://github.com/tristanpenman/valijson/blob/master/tests/test_jsoncpp_adapter.cpp#L15)
[line 49](https://github.com/tristanpenman/valijson/blob/master/tests/test_jsoncpp_adapter.cpp#L49)

**Comment by tristanpenman** [comment]
Thanks for pointing those out. I've fixed them in 0abf633.
