### ISSUE TITLE
valijson has no target

### ISSUE THREAD

**Issue by DonaldKevin** [tristanpenman/valijson#79]
You need to put something like this in your CMakeLists.txtx file

`# Modern CMake is about targets, and properties of targets; not flags.
`# A target can depend on other targets.
`# If there are no targets, you have only hidden dependencies.
`# add_dependencies(my_project PRIVATE valijson::valijson nlohmann_json::nlohmann_json ...)
`# target_link_libraries(my_project PRIVATE valijson::valijson nlohmann_json::nlohmann_json ...)
`add_library(valijson INTERFACE)
`add_library(valijson::valijson ALIAS valijson)
`target_sources(valijson INTERFACE include/valijson/validator.hpp)
`target_compile_features(valijson INTERFACE cxx_std_11)
`target_include_directories(valijson INTERFACE
`                          $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include/>
`                          $<INSTALL_INTERFACE:include/>)

**Comment by tristanpenman** [comment]
Hi Donald. I'm not really a CMake expert, so I'm not sure exactly what to change in the CMakeLists.txt file here. I am going close this issue for now, but feel free to raise a PR if you have some changes that have worked for your use case.
