### ISSUE TITLE
What is the point of constraints::PolyConstraint

### ISSUE THREAD

**Issue by myxo** [tristanpenman/valijson#82]
I see this constraint but seems it is not been used. At least it is not created anywhere.
Is it some left over code?

**Comment by tristanpenman** [comment]
It is best understood by looking at the PRs in which it was introduced:
https://github.com/tristanpenman/valijson/pulls?utf8=%E2%9C%93&q=is%3Apr+polyconstraint

Those PRs were raised by an engineer from Akamai, who wanted to support arbitrary constraints. These constraints would not be present in an ordinary JSON Schema, but could still be constructed programatically. I have no idea if this feature is still being used.
