### ISSUE TITLE
Question, Unknown Key in JSON

### ISSUE THREAD

**Issue by mohsenomidi** [tristanpenman/valijson#83]
Hi to all, 
Greetings!

Thanks for your great library, and contribution. 

I have just a question, is there any option in the library to identify the unknown key in JSON, I mean, if the key exists in input JSON but not defined in the schema the validator return an error. 

Regards,

**Comment by tristanpenman** [comment]
If you're using the master branch of Valijson, or the 0.2 release, this can be supported by adding `additionalProperties: false` to your schema. Say you had the following schema:
```
{
  "additionalProperties": false,
  "properties": {
    "hello": {
      "type": "string"
    }
  },
  "type": "object"
}
```
and validated the following document:
```
{
  "hello": "world",
  "foo": "bar"
}
```
you would get an error like this:
```
Validation failed.
Error #1
  context: <root>
  desc:    Object contains a property that could not be validated using 'properties' or 'additionalProperties' constraints: 'foo'.
```
Hopefully that answers your question. However, please let me know if I've misunderstood.

**Comment by mohsenomidi** [comment]
Hi @tristanpenman, 

Thanks So much for your complete and very useful example, it is great. 
and actually your explanation is my exact answer. 

Best Regards,
