### ISSUE TITLE
Does this support conditional evalutation (if, then, else)?

### ISSUE THREAD

**Issue by frazzyfin** [tristanpenman/valijson#85]
Referring to this: https://json-schema.org/understanding-json-schema/reference/conditionals.html

**Comment by tristanpenman** [comment]
This is currently supported in the https://github.com/tristanpenman/valijson/tree/v6-and-v7-support branch.

**Comment by frazzyfin** [comment]
Great! Any idea when this will be merged into master?

**Comment by tristanpenman** [comment]
v7 support is around 90% complete, but has been on the back burner for quite a while. It might make sense to just merge the parts that have been completed so far, and work from there. I'll take a look at it over the next few days and get back to you.

**Comment by frazzyfin** [comment]
Thanks

**Comment by tristanpenman** [comment]
After reviewing the v6-and-v7-support branch, I decided that it was good enough to merge into master.
