### ISSUE TITLE
Can I refer to a schema defined in another file?

### ISSUE THREAD

**Issue by wwriter** [tristanpenman/valijson#89]
Hi. First of all, thank you so much for maintaining this library.
I've been testing, using valijson to see if this meets my needs, and the experience has been pleasurable.

I am writing this post to ask you something.
This is the sketch of what I did, and what I wanted to do.
(I left out irrelevant data to make it concise)

I created `common.json` file to define a schema for common properties.
``` json
{
    "definitions" : {
        "common" : {
             "properties" : {
                    "ErrorCode" : { "type" : "number" },
                    "ErrorMessage" : { "type" : "string" }
             },
             "required" : [ "ErrorCode" ]
        }
    }
}
```

and I wanted to refer to the common properties defined in `common.json`, but nothing has worked so far.
`specific1.json` ( located : one level down )
``` json
{
    "properties" : {
         "Result" : {
                "allOf" : [
                      {"$ref" : "../common.json/definitions/common"},
                      {"properties" : "...properties that should be defined only in this context"}
                ]
         }
    }
}
```
(I used boost ptree to hold the schema, and the schema above leads to a stackoverflow error)

(If I added `#` right after `common.json`, it says
```expected reference token to identify an element in the current object , actual token : definitions```)

I am not sure if this is happening because I misused the syntax,
or because this feature is not supported.

Any help would be appreciated.

**Comment by tristanpenman** [comment]
Glad to hear your experience with the library has been positive so far!

While internal/local refs are pretty well supported, external/remote refs have always been a bit trickier. The file 'remote_resolution.cpp' in the examples directory shows how this can be done for URLs. Something similar should work for files.

I think it makes sense to include an example for your use-case, so I'll try coding one up and let you know.

**Comment by wwriter** [comment]
Thank you so much for your reply !
I'm sorry I should've given a more concrete use case.

Let's say that I send a request to ask what the time of the day is right now and get a response from there. 

```All``` response should have ```ResultCode``` field that indicates if the call was successful or not. [required]
```Some``` response could have ```ErrorString``` field that contains the message that tells you the cause of the error. [optional]

I thought those fields are quite common for a response data, so that I decided to define the schema for them in a ```ResponseSchema.json```.

Meanwhile there are fields that are only relevant to a specific function, which in this case, "CurrentTime" could be it.
So I will define it in another schema file only for ```GetCurrentTime``` function.
I'd like to point out the `CurrentTime` field is dependent on `ResultCode` field.
If the result code is other than zero, then it's okay if the response doesn't even have a key ```CurrentTime```.

```root/Schemas/CommonResponseProperties.json```
``` json
{
    "definitions" : {
        "common" : {
             "properties" : {
                    "ErrorCode" : { "type" : "number" },
                    "ErrorMessage" : { "type" : "string" }
             },
             "required" : [ "ErrorCode" ]
        }
    }
}
```

```root/Schemas/DateTime/GetCurrentTime.json```
``` json
{
    "properties" : {
        "Response" : {
             "descriptions" : "Response schema for GetCurrentTime function",
             "properties" : {
                  "ErrorCode" : {"$ref" : "not sure"},
                  "CurrentTime" : {"type" : "string"}
             }
        },
        "anyOf": [
            {
                "not": {
                      "properties": {
                             "ErrorCode": { "const": 0 }
                        },
                        "required" : []
                 }
             },
             { 
                 "required": ["CurrentTime"]
             }
        ]
}
```

If you look through ```Common.json```, ```GetCurrentTime.json```, ```main.cpp``` file that I attached,
I set the maximum constraint for ```ResultCode``` field, but the reference doesn't seem to work.

I'm sorry in advance if my explanation was too verbose or lengthy.

**Comment by tristanpenman** [comment]
I've hacked together a simple example case for this. It's a little sloppy, but might work for you. I've just pushed it, and you should find it at 'examples/remote_resolution_local_file.cpp'.

It works with something like the following two schema files.

schema1.json:
```
{
  "properties": {
    "hello": {
      "$ref": "file://./schema2.json#/definitions/hello"
    }
  },
  "type": "object"
}

```
schema2.json:
```
{
  "definitions": {
    "hello": {
      "type": "string"
    }
  }
}
```
Together, these will effectively form the schema:
```
{
  "properties": {
    "hello": {
       "type": "string"
    },
    "type": "object"
 }
```

The `file://` prefix is needed because the library is currently designed around the assumption that either a complete URI will be provided for JSON references, or the JSON reference refers to a node in the current document. The `fetchDocument` function in the example simply checks for this URI, and strips it out, before loading the file from disk.

Let me know if that works for you.

In the mean time, I'll try to tidy this up a bit more, and check what the specs say about how to handle this :)

**Comment by wwriter** [comment]
When I append ```file://``` prefix before the path, I get this error message.
```
Fetching of remote JSON References not enabled
```
It seems to be from ```schema_parser.hpp```

**Comment by tristanpenman** [comment]
Sorry, I should have been a bit more specific. There are two functions included in 'remote_resolution_local_file.cpp' which need to be added to your program: fetchDocument and freeDocument. In the example, those functions are provided to the parser on this line:
```
parser.populateSchema(schemaDocumentAdapter, schema, fetchDocument, freeDocument);
```
Once those functions are provided, support for remote JSON references will be enabled.

**Comment by wwriter** [comment]
Well, that worked !
I remember reading the line "the two functions should be provided" somewhere today,
but at that time I thought it was not relevant for my case.

Thank you again so so much for spending your time on this.
Now I can turn off my computer and go home ! 😀 😄
