### ISSUE TITLE
Error in file "property_tree_utils.hpp"?

### ISSUE THREAD

**Issue by davtorresg** [tristanpenman/valijson#9]
Hi,

I am trying to use your library using "ptree" of boost. In my example, I have included the file "property_tree_utils.hpp" and the code doesn't compile. The problem is that the header file "json.h" is being included. This file belongs to the "jsoncpp" third party.

Checking the code, I think that this include is not needed because here we are not using anything of "jsoncpp".

Kind regards,
David

**Comment by tristanpenman** [comment]
I've removed the unnecessary #include in commit 476d2c6. Hopefully that will resolve the issue for you.
