### ISSUE TITLE
Arguments of the constructors have the same name as the class members

### ISSUE THREAD

**Issue by jgmeinen** [tristanpenman/valijson#91]
The Arguments of the constructros have the same name as the class members. 
That leads to error messages from GCC :

`error: declaration of ‘description’ shadows a member of ‘valijson::Subschema’`

**Comment by tristanpenman** [comment]
Which version of GCC are you using? When I tried it with GCC 9.3.0 on Ubuntu 20.04, it didn't treat that as an error. I agree though, that shadowing is a bad idea, and intend to fix it. Just wanted to see the warning for myself first.

**Comment by jgmeinen** [comment]
I use `gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0` I use the -pedantic, -Wshadow, -Wunused and the -Werror flag, so warnings are treated as errors.

**Comment by tristanpenman** [comment]
Thanks, I'll enable those and tidy things up.

**Comment by tristanpenman** [comment]
Okay, I did a bit of a tidy up (touching many more lines of code than expected). And I've added those flags to the CMakeLists.txt file, so that the test suite makes use of them.

Please let me know if you discover any other warnings that haven't been covered yet.
