### ISSUE TITLE
Support for format

### ISSUE THREAD

**Issue by zhulik** [tristanpenman/valijson#98]
Hello, thanks for this awesome project!

Are there any plans to add support for `format`?

I'd like to build a ruby gem on top of your library and missing support for `format` is a real blocker for my use cases

Thank you!

**Comment by tristanpenman** [comment]
As far as I remember, the reason for lacking `format` support is that when I first started writing this library, it wasn't very well defined. And I had completely forgotten about it since then. I'll take a look at what will be involved in supporting it, and post any progress on this issue.

**Comment by zhulik** [comment]
@tristanpenman awesome, thank you! Here you can find q pure ruby imlementation that may be used as an example https://github.com/davishmcclurg/json_schemer/blob/master/lib/json_schemer/format.rb

**Comment by tristanpenman** [comment]
After reviewing this issue, I think the addition of date/time format support is probably going to cover the most important use-cases for the format constraint. I'm going to close this issue, but feel free to re-open it if you find that other formats would be valuable.
